name: Rust

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      - name: Tests
        run: cargo test --verbose
      - name: Test1
        run: if [ "$(echo -e 2 2 | cargo run)" = 4 ]; then echo "TEST 1 PASSED"; else echo "TEST 1 FAILED"; exit 105; fi
      - name: Test2
        run: if [ "$(echo -e 0 0 | cargo run)" = 0 ]; then echo "TEST 2 PASSED"; else echo "TEST 2 FAILED"; exit 105; fi
      - name: Test3
        run: if [ "$(echo -e -512324123 0 | cargo run)" = -512324123 ]; then echo "TEST 3 PASSED"; else echo "TEST 3 FAILED"; exit 105; fi
      - name: Test4
        run: if [ "$(echo -e -512324123 512324123 | cargo run)" = 0 ]; then echo "TEST 4 PASSED"; else echo "TEST 4 FAILED"; exit 105; fi
      - name: Test5
        run: if [ "$(echo -e -4 -5 | cargo run)" = -9 ]; then echo "TEST 5 PASSED"; else echo "TEST 5 FAILED"; exit 105; fi